### ISSUE TITLE
Elasticsearch logging does not work with datastreams

### ISSUE THREAD

**Issue by hahn-kev** [sgryphon/essential-logging#3]
Currently [here](https://github.com/sgryphon/essential-logging/blob/master/src/Essential.LoggerProvider.Elasticsearch/LoggerProvider/ElasticsearchDataProcessor.cs#L204) is calling index which does a `PUT /<target>/_doc/<_id>`

however when using a data-stream per this: https://www.elastic.co/guide/en/elasticsearch/reference/current/use-a-data-stream.html#add-documents-to-a-data-stream
that is not supported because a data-stream is read only and a put like we're doing can update a document. So we can either switch to call `TResponse Index<TResponse>(string index, PostData body, IndexRequestParameters requestParameters = null)` without specifying an ID, or call `Create<TResponse>(string index, string id, PostData body, CreateRequestParameters requestParameters = null)` and specify the op_type create (not sure how to do that).

**Comment by sgryphon** [comment]
The Elasticsearch logger provider has been moved to the ECS DotNet project.

Find the latest version here:
https://github.com/elastic/ecs-dotnet/blob/master/src/Elasticsearch.Extensions.Logging/ReadMe.md

The nuget package is here:
https://www.nuget.org/packages/Elasticsearch.Extensions.Logging/1.6.0-alpha1

Can you please see if the new project (which has an updated client handling the actual write) works of not; otherwise, raise the issue in the other project.  (The logger may still be using the same call, i.e. have the same issue, but this is now the wrong project).

**Comment by sgryphon** [comment]
I am going to close this issue; it may still be valid, but it needs to be raised in the other repository.

**Comment by hahn-kev** [comment]
@sgryphon I'm no longer at the company that I opened this issue for so I have no context to test it. However if its the same code then I would assume so.
